package br.edu.ifnmg.projeto_sorveteria.gui;

import br.edu.ifnmg.projeto_sorveteria.entidade.Adicional;
import br.edu.ifnmg.projeto_sorveteria.entidade.PedidoFisico;
import br.edu.ifnmg.projeto_sorveteria.entidade.Picole;
import br.edu.ifnmg.projeto_sorveteria.entidade.Sabor;
import br.edu.ifnmg.projeto_sorveteria.entidade.Tipo;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author felipess
 */

public class CadastrarPedido extends javax.swing.JInternalFrame {

    private static CadastrarPedido instance;
    private DefaultComboBoxModel<String> cboSaborModel;
    private DefaultComboBoxModel<String> cboAdicionalModel;
    private DefaultComboBoxModel<Tipo> cboTipoModel;
    private DefaultListModel<PedidoFisico> lstPedidoFisicoModel;
    private DefaultListModel<String> lstSaborModel;
    private DefaultListModel<String> lstAdicionalModel;
    private DefaultListModel<String> lstTipoModel;
    private DefaultListModel<Picole> lstPicoleModel;
    private Sabor sabor;
    private Adicional adicional;
    
    /**
     * Creates new form CadastrarPedido
     */
    public CadastrarPedido() {
        
        lstSaborModel = new DefaultListModel<>();
        lstAdicionalModel = new DefaultListModel<>();
        lstPicoleModel = new DefaultListModel<>();
        lstPedidoFisicoModel = new DefaultListModel<>();
        sabor = new Sabor();
        sabor.setNome("Morango");
        adicional = new Adicional();
        adicional.setNome("Granulado");
        cboSaborModel = new DefaultComboBoxModel<>();
        cboAdicionalModel = new DefaultComboBoxModel<>();
        cboTipoModel = new DefaultComboBoxModel<>(Tipo.values());
        cboSaborModel.addElement(sabor.getNome());
        cboAdicionalModel.addElement(adicional.getNome());

        initComponents();
    }
    
    static CadastrarPedido getInstance() {
              
        if (instance == null) {
            instance = new CadastrarPedido();
        }
        
        // TODO Carga de todas editoras e todos autores

        return instance;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tabPedido = new javax.swing.JTabbedPane();
        pnlInformacoes = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblPagamento = new javax.swing.JLabel();
        txtPagamento = new javax.swing.JTextField();
        dateChooserData = new com.toedter.calendar.JDateChooser();
        pnlProdutos = new javax.swing.JPanel();
        cboCategoria = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        scrlListProdutos = new javax.swing.JScrollPane();
        lstProdutos = new javax.swing.JList<>();
        pnlCategoria = new javax.swing.JPanel();
        pnlPicole = new javax.swing.JPanel();
        lblPicoleTipo = new javax.swing.JLabel();
        lblPicoleSabor = new javax.swing.JLabel();
        cboPicoleTipo = new javax.swing.JComboBox<>();
        cboPicoleSabor = new javax.swing.JComboBox<>();
        btnPicoleFinalizar = new javax.swing.JButton();
        pnlSorvete = new javax.swing.JPanel();
        lblSorveteRecipiente = new javax.swing.JLabel();
        cboSorveteRecipiente = new javax.swing.JComboBox<>();
        lblSorveteBolas = new javax.swing.JLabel();
        cboSorveteBolas = new javax.swing.JComboBox<>();
        btnSorveteProximo = new javax.swing.JButton();
        pnlSorvete2 = new javax.swing.JPanel();
        lblSorvete2Sabor = new javax.swing.JLabel();
        cboSorvete2Sabor = new javax.swing.JComboBox<>();
        btnSorvete2Proximo = new javax.swing.JButton();
        scrlListSorvete2Sabor = new javax.swing.JScrollPane();
        lstSorvete2Sabor = new javax.swing.JList<>();
        btnSorvete2Adicionar = new javax.swing.JButton();
        pnlSorvete3 = new javax.swing.JPanel();
        lblSorvete2Sabor2 = new javax.swing.JLabel();
        cboSorvete3Adicional = new javax.swing.JComboBox<>();
        scrlListSorvete2Sabor2 = new javax.swing.JScrollPane();
        lstSorvete3Adicional = new javax.swing.JList<>();
        btnSorvete3Adicionar = new javax.swing.JButton();
        btnSorvete3Finalizar = new javax.swing.JButton();
        pnlMilkshake = new javax.swing.JPanel();
        lblMilkshakeTamanho = new javax.swing.JLabel();
        cboMilkshakeTamanho = new javax.swing.JComboBox<>();
        btnFinalizarPedido = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Pedido");

        tabPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setText("Nome do Cliente");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setText("Data");

        lblPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPagamento.setText("Forma de Pagamento");

        txtPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlInformacoesLayout = new javax.swing.GroupLayout(pnlInformacoes);
        pnlInformacoes.setLayout(pnlInformacoesLayout);
        pnlInformacoesLayout.setHorizontalGroup(
            pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome)
                        .addComponent(txtPagamento)
                        .addGroup(pnlInformacoesLayout.createSequentialGroup()
                            .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addGroup(pnlInformacoesLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblData)
                                        .addComponent(dateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(4, 4, 4)))
                    .addComponent(lblPagamento))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        pnlInformacoesLayout.setVerticalGroup(
            pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(lblPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        tabPedido.addTab("Informações", pnlInformacoes);

        cboCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Picolé", "Sorvete", "Milkshake" }));
        cboCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboCategoriaActionPerformed(evt);
            }
        });

        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategoria.setText("Categoria");

        lstProdutos.setModel(lstPicoleModel);
        scrlListProdutos.setViewportView(lstProdutos);

        pnlCategoria.setLayout(new java.awt.CardLayout());

        lblPicoleTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPicoleTipo.setText("Tipo");

        lblPicoleSabor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPicoleSabor.setText("Sabor");

        cboPicoleTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboPicoleTipo.setModel(cboTipoModel);

        cboPicoleSabor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboPicoleSabor.setModel(cboSaborModel);

        btnPicoleFinalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPicoleFinalizar.setText("Finalizar produto");
        btnPicoleFinalizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPicoleFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPicoleLayout = new javax.swing.GroupLayout(pnlPicole);
        pnlPicole.setLayout(pnlPicoleLayout);
        pnlPicoleLayout.setHorizontalGroup(
            pnlPicoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPicoleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPicoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicoleSabor)
                    .addComponent(cboPicoleTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPicoleSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPicoleTipo))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPicoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPicoleFinalizar)
                .addContainerGap())
        );
        pnlPicoleLayout.setVerticalGroup(
            pnlPicoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPicoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPicoleTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPicoleTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPicoleSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPicoleSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPicoleFinalizar)
                .addGap(61, 61, 61))
        );

        pnlCategoria.add(pnlPicole, "picole");

        lblSorveteRecipiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSorveteRecipiente.setText("Recipiente");

        cboSorveteRecipiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSorveteRecipiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSorveteBolas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSorveteBolas.setText("Quantidade de Bolas");

        cboSorveteBolas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSorveteBolas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", " " }));
        cboSorveteBolas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboSorveteBolasActionPerformed(evt);
            }
        });

        btnSorveteProximo.setText(">");
        btnSorveteProximo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSorveteProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSorveteLayout = new javax.swing.GroupLayout(pnlSorvete);
        pnlSorvete.setLayout(pnlSorveteLayout);
        pnlSorveteLayout.setHorizontalGroup(
            pnlSorveteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorveteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSorveteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSorveteBolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSorveteBolas)
                    .addComponent(lblSorveteRecipiente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSorveteRecipiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSorveteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSorveteProximo)
                .addContainerGap())
        );
        pnlSorveteLayout.setVerticalGroup(
            pnlSorveteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorveteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSorveteRecipiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSorveteRecipiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSorveteBolas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboSorveteBolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnSorveteProximo)
                .addGap(49, 49, 49))
        );

        pnlCategoria.add(pnlSorvete, "sorvete");

        pnlSorvete2.setToolTipText("Teste");

        lblSorvete2Sabor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSorvete2Sabor.setText("Sabor");

        cboSorvete2Sabor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSorvete2Sabor.setModel(cboSaborModel);
        cboSorvete2Sabor.setToolTipText("");

        btnSorvete2Proximo.setText(">");
        btnSorvete2Proximo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSorvete2ProximoActionPerformed(evt);
            }
        });

        lstSorvete2Sabor.setModel(lstSaborModel);
        scrlListSorvete2Sabor.setViewportView(lstSorvete2Sabor);

        btnSorvete2Adicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSorvete2Adicionar.setText("+");
        btnSorvete2Adicionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSorvete2AdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSorvete2Layout = new javax.swing.GroupLayout(pnlSorvete2);
        pnlSorvete2.setLayout(pnlSorvete2Layout);
        pnlSorvete2Layout.setHorizontalGroup(
            pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorvete2Layout.createSequentialGroup()
                .addGroup(pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSorvete2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSorvete2Proximo))
                    .addGroup(pnlSorvete2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlListSorvete2Sabor, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addGroup(pnlSorvete2Layout.createSequentialGroup()
                                .addGroup(pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSorvete2Sabor)
                                    .addGroup(pnlSorvete2Layout.createSequentialGroup()
                                        .addComponent(cboSorvete2Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSorvete2Adicionar)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlSorvete2Layout.setVerticalGroup(
            pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorvete2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSorvete2Sabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSorvete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSorvete2Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSorvete2Adicionar))
                .addGap(18, 18, 18)
                .addComponent(scrlListSorvete2Sabor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSorvete2Proximo)
                .addGap(49, 49, 49))
        );

        pnlCategoria.add(pnlSorvete2, "sorvete2");

        lblSorvete2Sabor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSorvete2Sabor2.setText("Adicionais");

        cboSorvete3Adicional.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSorvete3Adicional.setModel(cboAdicionalModel);
        cboSorvete3Adicional.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cboSorvete3AdicionalActionPerformed(evt);
            }
        });

        lstSorvete3Adicional.setModel(lstAdicionalModel);
        scrlListSorvete2Sabor2.setViewportView(lstSorvete3Adicional);

        btnSorvete3Adicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSorvete3Adicionar.setText("+");
        btnSorvete3Adicionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSorvete3AdicionarActionPerformed(evt);
            }
        });

        btnSorvete3Finalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSorvete3Finalizar.setText("Finalizar produto");

        javax.swing.GroupLayout pnlSorvete3Layout = new javax.swing.GroupLayout(pnlSorvete3);
        pnlSorvete3.setLayout(pnlSorvete3Layout);
        pnlSorvete3Layout.setHorizontalGroup(
            pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorvete3Layout.createSequentialGroup()
                .addGroup(pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSorvete3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlListSorvete2Sabor2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addGroup(pnlSorvete3Layout.createSequentialGroup()
                                .addGroup(pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSorvete2Sabor2)
                                    .addGroup(pnlSorvete3Layout.createSequentialGroup()
                                        .addComponent(cboSorvete3Adicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSorvete3Adicionar)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSorvete3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSorvete3Finalizar)))
                .addContainerGap())
        );
        pnlSorvete3Layout.setVerticalGroup(
            pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSorvete3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSorvete2Sabor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSorvete3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSorvete3Adicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSorvete3Adicionar))
                .addGap(18, 18, 18)
                .addComponent(scrlListSorvete2Sabor2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(btnSorvete3Finalizar)
                .addContainerGap())
        );

        pnlCategoria.add(pnlSorvete3, "sorvete3");

        lblMilkshakeTamanho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMilkshakeTamanho.setText("Tamanho do Copo");

        cboMilkshakeTamanho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboMilkshakeTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlMilkshakeLayout = new javax.swing.GroupLayout(pnlMilkshake);
        pnlMilkshake.setLayout(pnlMilkshakeLayout);
        pnlMilkshakeLayout.setHorizontalGroup(
            pnlMilkshakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMilkshakeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMilkshakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMilkshakeTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMilkshakeTamanho))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        pnlMilkshakeLayout.setVerticalGroup(
            pnlMilkshakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMilkshakeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMilkshakeTamanho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboMilkshakeTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pnlCategoria.add(pnlMilkshake, "milkshake");

        btnFinalizarPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFinalizarPedido.setText("Finalizar pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlListProdutos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                        .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(pnlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizarPedido)))
                .addContainerGap())
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdutosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlListProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnFinalizarPedido)
                .addGap(111, 111, 111))
        );

        tabPedido.addTab("Produtos", pnlProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPedido)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        
        Integer indice = cboCategoria.getSelectedIndex();
        CardLayout cardLayout; 

        cardLayout = (CardLayout) pnlCategoria.getLayout();

        if(indice == 0)
            cardLayout.show(pnlCategoria, "picole");

        if(indice == 1)
            cardLayout.show(pnlCategoria, "sorvete");

        if(indice == 2)
            cardLayout.show(pnlCategoria, "milkshake");
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void btnSorvete2ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorvete2ProximoActionPerformed

        if(lstSaborModel.getSize() <= cboSorveteBolas.getSelectedIndex() + 1){
       
            CardLayout cardLayout; 

            cardLayout = (CardLayout) pnlCategoria.getLayout();

            cardLayout.show(pnlCategoria, "sorvete3");
        }

    }//GEN-LAST:event_btnSorvete2ProximoActionPerformed

    private void btnSorveteProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorveteProximoActionPerformed
        
        CardLayout cardLayout; 

        cardLayout = (CardLayout) pnlCategoria.getLayout();

        cardLayout.show(pnlCategoria, "sorvete2");
    }//GEN-LAST:event_btnSorveteProximoActionPerformed

    private void btnSorvete2AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorvete2AdicionarActionPerformed

        lstSaborModel.addElement((String) cboSorvete2Sabor.getSelectedItem());
    }//GEN-LAST:event_btnSorvete2AdicionarActionPerformed

    private void cboSorvete3AdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSorvete3AdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSorvete3AdicionalActionPerformed

    private void btnSorvete3AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorvete3AdicionarActionPerformed
       
        lstAdicionalModel.addElement((String) cboSorvete3Adicional.getSelectedItem());
    }//GEN-LAST:event_btnSorvete3AdicionarActionPerformed

    private void cboSorveteBolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSorveteBolasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSorveteBolasActionPerformed

    private void btnPicoleFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPicoleFinalizarActionPerformed

        Picole picole = new Picole();
        Sabor sabor = new Sabor();
        picole.setTipo((Tipo) cboTipoModel.getSelectedItem());
        sabor.setNome((String) cboSaborModel.getSelectedItem());
        picole.setSabor(sabor);
        
        lstPicoleModel.addElement(picole);
    }//GEN-LAST:event_btnPicoleFinalizarActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        
        PedidoFisico pf = new PedidoFisico();
        pf.setCliente(txtNome.getText());

        Date data = new Date();
        data = dateChooserData.getDate();
        
        LocalDate date = LocalDate.ofInstant(data.toInstant(), ZoneId.systemDefault());
        
        date.atStartOfDay();
        
        pf.setData(LocalDateTime.MAX);   
                        
        lstPedidoFisicoModel.addElement(pf);
        
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnPicoleFinalizar;
    private javax.swing.JButton btnSorvete2Adicionar;
    private javax.swing.JButton btnSorvete2Proximo;
    private javax.swing.JButton btnSorvete3Adicionar;
    private javax.swing.JButton btnSorvete3Finalizar;
    private javax.swing.JButton btnSorveteProximo;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboMilkshakeTamanho;
    private javax.swing.JComboBox<String> cboPicoleSabor;
    private javax.swing.JComboBox<Tipo> cboPicoleTipo;
    private javax.swing.JComboBox<String> cboSorvete2Sabor;
    private javax.swing.JComboBox<String> cboSorvete3Adicional;
    private javax.swing.JComboBox<String> cboSorveteBolas;
    private javax.swing.JComboBox<String> cboSorveteRecipiente;
    private com.toedter.calendar.JDateChooser dateChooserData;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMilkshakeTamanho;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPicoleSabor;
    private javax.swing.JLabel lblPicoleTipo;
    private javax.swing.JLabel lblSorvete2Sabor;
    private javax.swing.JLabel lblSorvete2Sabor2;
    private javax.swing.JLabel lblSorveteBolas;
    private javax.swing.JLabel lblSorveteRecipiente;
    private javax.swing.JList<Picole> lstProdutos;
    private javax.swing.JList<String> lstSorvete2Sabor;
    private javax.swing.JList<String> lstSorvete3Adicional;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlInformacoes;
    private javax.swing.JPanel pnlMilkshake;
    private javax.swing.JPanel pnlPicole;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JPanel pnlSorvete;
    private javax.swing.JPanel pnlSorvete2;
    private javax.swing.JPanel pnlSorvete3;
    private javax.swing.JScrollPane scrlListProdutos;
    private javax.swing.JScrollPane scrlListSorvete2Sabor;
    private javax.swing.JScrollPane scrlListSorvete2Sabor2;
    private javax.swing.JTabbedPane tabPedido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPagamento;
    // End of variables declaration//GEN-END:variables
}
